LIBS=-lelliptics -lelliptics_cpp -leblob -lboost_system-mt -lboost_thread-mt -lgrapejson

all: archive

archive: <{node_config.soname}>
	tar -cf <{node_config.tar_name}> <{node_config.soname}>

<{node_config.soname}>: test.o
	c++ -fPIC -shared -o <{node_config.soname}> test.o /usr/lib/libgrape.so $(LIBS)

test.o: test.cpp
	c++  -fPIC -std=c++0x -o test.o -c test.cpp